module Life
  class CLI
    OUTPUT_FILE: String

    def version: () -> void
    def start: () -> void

    # Thor methods
    def self.desc: (String, String, ?String) -> void
    def self.default_task: (Symbol) -> void
    def self.map: (Hash[String | Array[String], Symbol]) -> void
    def self.option: (Symbol, Hash[Symbol, untyped]) -> void
    def options: () -> Hash[Symbol | String, untyped]

    private

    def clear_screen: () -> void
    def check_start_options: (Hash[Symbol | String, untyped]) -> void
  end
end
