name: CI

on:
  - push
  - pull_request

jobs:
  spec:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby:
          - 3.1
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake spec
